name: "Set Issue Label"
on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Amwam/issue-comment-action@997c3ccaaec8035843469fd80159a1613bcfd5e1
        with:
          keywords: '["/test"]'
          labels: '["test"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
